iwebexpert/corp-rostelecom-1

lesson3_1.html
lesson3_2.html
lesson3_3.html
lesson3_4.html

Homework lesson3 Artem Grebenyuk

---

Aksenova A/lesson3/lesson3.js

my hw - lesson 3 js

---

Sergey_Nikitin/lesson4/lesson4_1.html
Sergey_Nikitin/lesson4/lesson4_2.html
Sergey_Nikitin/lesson4/lesson4_2_ES5.html
Sergey_Nikitin/lesson4/lesson4_3.html

ДЗ от 4 урока. по классам реализовано 2 варината es5 и es6.

lesson 4 homework

---

Vyacheslav_Kulik/lession 4/HomeWork41.html
Vyacheslav_Kulik/lession 4/ShopObject.html
Vyacheslav_Kulik/lession3/Shop.html

Vyacheslav_Kulik/lession 4/HomeWork41.html - задание №1 (Написать функцию, преобразующую число в объект);
Vyacheslav_Kulik/lession 4/ShopObject.html - задание №2 (Магазин на базе ООП);
Задание со *: Вероятно тут речь идет о том, чтобы продумать все объекты для конечного продукта и спроектировать их так, чтобы исключить копирование кода и создание лишних методов. 
Во втором задании я создал класс Item (Товары интернет магазина). Его можно дописать, добавив нужные свойства и методы, чтобы использовать их для  выдачи в каталоге. 
Для "Корзины" я решил использовать объект "shoppingCart", так как на сайте как правило одна корзина в рамках сессии пользователя (создание отдельного класса избыточно). Внутри методов "shoppingCart" используются методы "Item" (this.items[i][0].show()), а так же …

HomeWork Lession4 from Kulik Vyacheslav

---

Sergey_Nikitin/lesson5/Lesson5_1.css
Sergey_Nikitin/lesson5/Lesson5_1.html
Sergey_Nikitin/lesson5/Lesson5_1.js
Sergey_Nikitin/lesson5/Lesson5_2_3.css
Sergey_Nikitin/lesson5/Lesson5_2_3.html
Sergey_Nikitin/lesson5/Lesson5_2_3.js

Lesson 5 homework

---

Vyacheslav_Kulik/lession 5/Chess.html
Vyacheslav_Kulik/lession 5/ShopObject.html

Vyacheslav_Kulik/lession 5/Chess.html - Задание 1 (Создать функцию, генерирующую шахматную доску);
Vyacheslav_Kulik/lession 5/ShopObject.html - Задание 2 и 3* (Список всех товаров +  Корзина).

HomeWork Lession5 from Kulik Vyacheslav

---

sml/lesson5/basket/basket.css
sml/lesson5/basket/basket.html
sml/lesson5/basket/basket.js
sml/lesson5/chess/chess.css
sml/lesson5/chess/chess.html
sml/lesson5/chess/chess.js

Домашняя работа 5
Задание 1 ------
chess\chess.js
chess\chess.css
chess\chess.html
Задание 2 ------
basket\basket.js
basket\basket.css
basket\basket.html

Homework5 

---

Sergey_Nikitin/lesson6/Lesson6.css
Sergey_Nikitin/lesson6/Lesson6.html
Sergey_Nikitin/lesson6/Lesson6.js

6.1 скопировано с пред задания со * + добавлено 6.2

lesson 6 homework

---

Olga_Kiseleva/lesson6/ShopOkis

Можно ли как-нибудь объединить строки 223-236? (по сути делают одно и тоже, но выборка идет по разным классам).

ShopOkis_lesson6

---

5_1.html
Basket.html
Event.html
main.js
main1.js
style.css
style1.css

Я написал несколько вопросов по второму заданию, просьба посмотреть и ответить

Homework for 5,6 lesson

---

Vyacheslav Beketov/Lesson5/index.html

Домашнее задание к Лекции 5 index.html

---

Vyacheslav Beketov/Lesson5/main.js

Домашнее задание к Лекции 5 main.js

---

Vyacheslav Beketov/Lesson5/style.css

Домашнее задание к Лекции 5  style.css

---

Sergey_Nikitin/lesson6/Lesson6.js
Sergey_Nikitin/lesson7/Lesson7.css
Sergey_Nikitin/lesson7/Lesson7.html
Sergey_Nikitin/lesson7/Lesson7.js
Sergey_Nikitin/lesson7/game_lesson7_3/index.html
Sergey_Nikitin/lesson7/game_lesson7_3/src/Board.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Food.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Game.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Main.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Menu.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Settings.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Snake.js
Sergey_Nikitin/lesson7/game_lesson7_3/src/Status.js
Sergey_Nikitin/lesson7/game_lesson7_3/style.css

7.3 в отдельной папке. остальное в корне.

lesson7 homework

---

Ovchinnikov_Pavel/Lesson-7/Basket.js
Ovchinnikov_Pavel/Lesson-7/Helper.js
Ovchinnikov_Pavel/Lesson-7/Main.js
Ovchinnikov_Pavel/Lesson-7/Product.js
Ovchinnikov_Pavel/Lesson-7/Products.js
Ovchinnikov_Pavel/Lesson-7/lesson_7.html
Ovchinnikov_Pavel/Lesson-7/mein.css
Ovchinnikov_Pavel/Lesson-7/webBasket.css
Ovchinnikov_Pavel/Lesson-7/webBasket.js
Ovchinnikov_Pavel/Lesson-7/webModal.css
Ovchinnikov_Pavel/Lesson-7/webModal.js
Ovchinnikov_Pavel/Lesson-7/webСatalog.css
Ovchinnikov_Pavel/Lesson-7/webСatalog.js

1. Разбил всё на классы (все классы в отдельном файле дял удобства сопровождения), для этого пришлось всё переписать с чистого листа.
2. Удалять данные из корзины можно как через каталог, так и через корзину.
3. При нажатии на мини-картинку товара в каталоге, открывается ее полноразмерная копия в диалоге, при этом в диалоге нужная пиктограмма подсвечивается.
4. В диалоге картинки можно пролистывать тремя способами: через кнопки на клавиатуре, через нажатия на кнопки влево, вправо в окне диалоге или при нажатии на нужную пиктограмму картинки в диалоге. при этом в диалоге соответствующая пиктограмма подсвечивается.
5. Диалоговое окно закрывается через кнопку-крестик в окне или при нажатии кнопку Esc на клавиатуре.
6. Чтобы посмотреть содержимое корзины необходимо нажать на п.меню "Состав …

ДЗ к уроку №7

---

smirnov-alex/lesson5/basket.js

Промежуточный вариант между 3-м заданием со звездочкой и ДЗ шестого задания. Потерял много времени на обработчиках событий, оказалось, что это тема следующего урока.

Homework5, basket.js

---

Dmitry_Baranov/lesson6/js/shop.js
Dmitry_Baranov/lesson7/game/index.html
Dmitry_Baranov/lesson7/game/src/Board.js
Dmitry_Baranov/lesson7/game/src/Food.js
Dmitry_Baranov/lesson7/game/src/Game.js
Dmitry_Baranov/lesson7/game/src/Main.js
Dmitry_Baranov/lesson7/game/src/Menu.js
Dmitry_Baranov/lesson7/game/src/Settings.js
Dmitry_Baranov/lesson7/game/src/Snake.js
Dmitry_Baranov/lesson7/game/src/Status.js
Dmitry_Baranov/lesson7/game/style.css
Dmitry_Baranov/lesson7/js/modal.js
Dmitry_Baranov/lesson7/js/shop.js
Dmitry_Baranov/lesson7/shop.html
Dmitry_Baranov/lesson7/style/shop.css

Задания 7.1 7.2 7.3 
Магазин без реализации слайдера.
Игорь, у меня почему-то при загрузке страницы браузер перескакивает примерно на середину странички, не пойму из-за чего это происходит.

Home work 7

---

Sergey_Nikitin/Lesson8/lesson8.html

ответы на задание в комментариях

lesson8 homework

---

dz_7/index7.html
dz_7/js7.js
dz_7/style7.css

Неправильно работает удаление из корзины. Пока не нашёл ошибку.

homework_7 V.Loginov

---

Ovchinnikov_Pavel/Lesson-9/hamburger​.js
Ovchinnikov_Pavel/Lesson-9/helper.js
Ovchinnikov_Pavel/Lesson-9/lesson_9.html
Ovchinnikov_Pavel/Lesson-9/style.css

1. Корзина и каталог были реализованы ранее (https://github.com/iwebexpert/corp-rostelecom-1/pull/111)
2. Реализован расчет стоимости и калорийности гамбургера. Расчет выводится на страницу в браузере.

ДЗ к уроку № 9

---

Sergey_Nikitin/lesson9/Lesson9.css
Sergey_Nikitin/lesson9/Lesson9.html
Sergey_Nikitin/lesson9/Lesson9.js

по сути задние 7. там уже используются классы.

Lesson 9 Homework

---

Olga_Kiseleva/lesson9/ShopOkis.html
Olga_Kiseleva/lesson9/shop.js
Olga_Kiseleva/lesson9/style.css

Прошу Вас не обращать внимание на все что связано с productsBasket в классе Catalog (стр. 17 и 19 в файле shop.js)
Вопрос: если бы класс Basket наследовался от класса Catalog, можно ли было в Basket работать с переменной products, если "да", то как? (иными словами можно ли получать значения переменных из родительского класса или род. класс нужен только для создания структуры и "общих" функций?)

lesson9_Okis

---

Ovchinnikov_Pavel/Lesson-10/Basket.js
Ovchinnikov_Pavel/Lesson-10/Helper.js
Ovchinnikov_Pavel/Lesson-10/Main.js
Ovchinnikov_Pavel/Lesson-10/Product.js
Ovchinnikov_Pavel/Lesson-10/Products.js
Ovchinnikov_Pavel/Lesson-10/db.json
Ovchinnikov_Pavel/Lesson-10/lesson_10.html
Ovchinnikov_Pavel/Lesson-10/mein.css
Ovchinnikov_Pavel/Lesson-10/webBasket.css
Ovchinnikov_Pavel/Lesson-10/webBasket.js
Ovchinnikov_Pavel/Lesson-10/webModal.css
Ovchinnikov_Pavel/Lesson-10/webModal.js
Ovchinnikov_Pavel/Lesson-10/webСatalog.css
Ovchinnikov_Pavel/Lesson-10/webСatalog.js

БД товаров вынесена в файл db.json.
Изменения кода коснулись модуля Main.js, где список товаров получается асинхронным запросом от сервера.

ДЗ к уроку № 10

---

Dmitry_Baranov/lesson7/js/modal.js
Dmitry_Baranov/lesson7/js/shop.js
Dmitry_Baranov/lesson7/style/shop.css
Dmitry_Baranov/lesson9/hamburger.html
Dmitry_Baranov/lesson9/js/hamburger.js
Dmitry_Baranov/lesson9/js/main.js
Dmitry_Baranov/lesson9/style/style.css

Home work 9

---

Sergey_Nikitin/lesson10/Lesson10.css
Sergey_Nikitin/lesson10/Lesson10.html
Sergey_Nikitin/lesson10/Lesson10.js
Sergey_Nikitin/lesson10/db.json

основной код взят из 9 задания
1 выполнено через fetch
2 было и раньше
3* сделано как пример без отрисовки

lesson 10 homework

---

Aleksandr_Koposov/node1/package-lock.json
Aleksandr_Koposov/node1/package.json
Aleksandr_Koposov/node1/src/_colors.js
Aleksandr_Koposov/node1/src/task2.js
Aleksandr_Koposov/node1/src/task3.js
Aleksandr_Koposov/node2/package-lock.json
Aleksandr_Koposov/node2/package.json
Aleksandr_Koposov/node2/src/task1.js
Aleksandr_Koposov/node2/src/task2.js
Aleksandr_Koposov/node2/static/index.html

Node - ДЗ 1 и 2

---

Vyacheslav_Kulik/lesson 13/colorConsole.js
Vyacheslav_Kulik/lesson 13/headsOrTails.js
Vyacheslav_Kulik/lesson 13/package-lock.json
Vyacheslav_Kulik/lesson 13/package.json

Vyacheslav_Kulik/lesson 13/colorConsole.js - задание 2, выводит в консоль разным цветом то, что было введено в нее
Vyacheslav_Kulik/lesson 13/headsOrTails.js - игра "Орел или Решка"

HomeWork Lesson 13 from Kulik Vyacheslav

---

Ovchinnikov_Pavel/Lesson-13_Node/Game.js
Ovchinnikov_Pavel/Lesson-13_Node/package-lock.json
Ovchinnikov_Pavel/Lesson-13_Node/package.json

2 и 3 задание реализовано в одном приложении Game.js

ДЗ к уроку № 13 (Node.js)

---

Alexandr-Grigorev/node1/orel-i-reshka/game.js
Alexandr-Grigorev/node1/orel-i-reshka/package-lock.json
Alexandr-Grigorev/node1/orel-i-reshka/package.json

Использовал вывод разными цветами в Орел и решка

Node.js -1

---

Igor_Ovchinin/node js/lesson 1/ansi.js
Igor_Ovchinin/node js/lesson 1/chalk.js
Igor_Ovchinin/node js/lesson 1/express.js
Igor_Ovchinin/node js/lesson 1/httpServer.js
Igor_Ovchinin/node js/lesson 1/nodeStatic.js
Igor_Ovchinin/node js/lesson 1/package-lock.json
Igor_Ovchinin/node js/lesson 1/package.json
Igor_Ovchinin/node js/lesson 1/readline.js
Igor_Ovchinin/node js/lesson 1/www/index.html
Igor_Ovchinin/node js/lesson 1/www/test.html

1) Запустил код с урока
2) Преобразовал вывод данных в консоль с помощью пакета "chalk", создал отдельный файл для него
3) Дописал генерацию случайных чисел для игры "Орел или решка"

Node.js ДЗ №1

---

Vyacheslav_Kulik/lesson 14/getFileInfoYaDisk.js
Vyacheslav_Kulik/lesson 14/package-lock.json
Vyacheslav_Kulik/lesson 14/package.json
Vyacheslav_Kulik/lesson 14/parserLenta.js
Vyacheslav_Kulik/lesson 14/translater.js

Vyacheslav_Kulik/lesson 14/parserLenta.js - Парсер сайта lenta.ru (задание 1);
Vyacheslav_Kulik/lesson 14/translater.js - Переводчик с Английского на Русский с использованием API Google. API на пакете "google-translate-api-browser" (задание 2);
Vyacheslav_Kulik/lesson 14/getFileInfoYaDisk.js - информация о файле с Ягдекс.Диска. Запускать с ключем --file=. Если не указать ключ, то покажет подсказку (задание 2+).

HomeWork Lession 14 from Kulik Vyacheslav

---

Sergey_Nikitin/lesson14/homeWork_14_1.js
Sergey_Nikitin/lesson14/homeWork_14_2.js
Sergey_Nikitin/lesson14/httpsRequest.js
Sergey_Nikitin/lesson14/mail.js
Sergey_Nikitin/lesson14/package-lock.json
Sergey_Nikitin/lesson14/package.json
Sergey_Nikitin/lesson14/yaDisk.js

Lesson 14 homework

---

Ovchinnikov_Pavel/Lesson-14_Node/GoogleTranslate.js
Ovchinnikov_Pavel/Lesson-14_Node/PullNews.js
Ovchinnikov_Pavel/Lesson-14_Node/package.json

PullNews.js - получение новостей с сайтов Яндекса, Майл.ру и Лента.ру (через async/await)
Список команд:
? help h - Вызов справки по командам
1 - Новости от Яндекс.ру
2 - Новости от Майл.ру
3 - Новости от Лента.ру
'*' - Все новости
Прочие команды - Выход из приложения
GoogleTranslate.js - перевод En  --> Ru через пакет "google-translate-free"
хотел и следующий блок завернуть через await, но наткнулся на ошибку "Promise { <pending> }", на разбор нет пока времени, поэтому упростил код:
translate(str, { from: 'en', to: 'ru' }).then(res => {
console.log(textRu("Перевод: ") + res.text);
read.setPrompt(strPrompt)
read.prompt()
});

ДЗ к уроку № 14 (Node.js)

---

Aleksandr_Koposov/node3/package-lock.json
Aleksandr_Koposov/node3/package.json
Aleksandr_Koposov/node3/src/main.js
Aleksandr_Koposov/node3/views/index.hbs
Aleksandr_Koposov/node3/views/news.hbs

Два задания в одном файле. Пагинация новостей не запросом, ибо не везде есть она в RSS, а на стороне сервера.

Node - ДЗ 3

---

Sergei_Gerashchenko/nodejs/lesson2/express.js
Sergei_Gerashchenko/nodejs/lesson2/parse.js
Sergei_Gerashchenko/nodejs/lesson2/views/layouts/default.hbs
Sergei_Gerashchenko/nodejs/lesson2/views/news.hbs

Не до конца разобрался, как выводить список новостей, поскольку получаются они в асинхронном режиме. Форму и куки сделал

Homework15

---

Aleksandr_Koposov/node3/src/main.js

Добавлена кроссплатформенность путей

Node - ДЗ 3 - Fix Path

---

.vscode/settings.json
Aleksandr_Koposov/node4/models/todo.js
Aleksandr_Koposov/node4/models/users.js
Aleksandr_Koposov/node4/package-lock.json
Aleksandr_Koposov/node4/package.json
Aleksandr_Koposov/node4/src/auth.js
Aleksandr_Koposov/node4/src/config.js
Aleksandr_Koposov/node4/src/main.js
Aleksandr_Koposov/node4/views/index.hbs
Aleksandr_Koposov/node4/views/login.hbs
Aleksandr_Koposov/node4/views/register.hbs

Список дел с авторизацией. Без привязки к пользователю.

Node - ДЗ 4 и 5

---

Sergey_Nikitin/lesson18/auth.js
Sergey_Nikitin/lesson18/data/users.js
Sergey_Nikitin/lesson18/express.js
Sergey_Nikitin/lesson18/models/chats.js
Sergey_Nikitin/lesson18/models/messages.js
Sergey_Nikitin/lesson18/models/toDoList.js
Sergey_Nikitin/lesson18/models/users.js
Sergey_Nikitin/lesson18/package-lock.json
Sergey_Nikitin/lesson18/package.json
Sergey_Nikitin/lesson18/public/main.css
Sergey_Nikitin/lesson18/public/main.js

ДЗ сделано путем обновления кода предыдущего ДЗ,
файл express.js
реализовано Rest.API

Lesson 18 Homework

---

Vyacheslav_Kulik/lesson 18/app.js
Vyacheslav_Kulik/lesson 18/models/todoitems.js
Vyacheslav_Kulik/lesson 18/models/todolist.js
Vyacheslav_Kulik/lesson 18/public/main.css
Vyacheslav_Kulik/lesson 18/public/todo.js
Vyacheslav_Kulik/lesson 18/www/todo.html
Vyacheslav_Kulik/lesson 19/app.js
Vyacheslav_Kulik/lesson 19/models/todoitems.js
Vyacheslav_Kulik/lesson 19/models/todolist.js
Vyacheslav_Kulik/lesson 19/models/users.js
Vyacheslav_Kulik/lesson 19/package-lock.json
Vyacheslav_Kulik/lesson 19/package.json
Vyacheslav_Kulik/lesson 19/public/logout.js
Vyacheslav_Kulik/lesson 19/public/main.css
Vyacheslav_Kulik/lesson 19/public/main.js
Vyacheslav_Kulik/lesson 19/public/todo.js
Vyacheslav_Kulik/lesson 19/www/index.html
Vyacheslav_Kulik/lesson 19/www/logout.html
Vyacheslav_Kulik/lesson 19/www/reg.html
Vyacheslav_Kulik/lesson 19/www/todo.html

Точка входа: http://localhost:4000/auth
Работает синхронизация всех действий между открытыми вкладками:
- удаление;
- добавление;
- изменение;
- выполнение.

HomeWork lesson 19. WebSocket for ToDoList. Kulik Vyacheslav

---

Sergey_Nikitin/lesson19/auth.js
Sergey_Nikitin/lesson19/data/users.js
Sergey_Nikitin/lesson19/express.js
Sergey_Nikitin/lesson19/models/chats.js
Sergey_Nikitin/lesson19/models/messages.js
Sergey_Nikitin/lesson19/models/toDoList.js
Sergey_Nikitin/lesson19/models/users.js
Sergey_Nikitin/lesson19/package-lock.json
Sergey_Nikitin/lesson19/package.json
Sergey_Nikitin/lesson19/public/main.css
Sergey_Nikitin/lesson19/public/main.js
Sergey_Nikitin/lesson19/websocket/auth.html
Sergey_Nikitin/lesson19/websocket/index.html

За основу взято предыдущее  дз и реализованы сокеты.
Методы: добавление, удаление , переключение
Код в основном express.js и index.html

Lesson 19 HomeWork

---

Oleg_Kirpikov/Node7/config.js
Oleg_Kirpikov/Node7/models/tasks.js
Oleg_Kirpikov/Node7/models/users.js
Oleg_Kirpikov/Node7/package-lock.json
Oleg_Kirpikov/Node7/package.json
Oleg_Kirpikov/Node7/public/actors.js
Oleg_Kirpikov/Node7/public/client.htm
Oleg_Kirpikov/Node7/public/main.css
Oleg_Kirpikov/Node7/public/main.js
Oleg_Kirpikov/Node7/todolist-websocket.js

todolist-websocket.js  запускает сразу два сервера
webserver  http://localhost:4000
websocket  ws://localhost:5000
client: http://localhost:4000/client.htm

Node js 7 websocket server: todolist-websocket.js

---

Serg.Ivanov/Lesson_20/package-lock.json
Serg.Ivanov/Lesson_20/package.json
Serg.Ivanov/Lesson_20/src/index.html
Serg.Ivanov/Lesson_20/src/index.js
Serg.Ivanov/Lesson_20/webpack.config.js

Добавлена кнопка наполнения массива
Содержимое отдается в консоль
Вывести на страницу не вышло.

React Lesson_20

---

Sergey_Nikitin/lesson20/package-lock.json
Sergey_Nikitin/lesson20/package.json
Sergey_Nikitin/lesson20/src/index.html
Sergey_Nikitin/lesson20/src/index.js
Sergey_Nikitin/lesson20/webpack.config.js

Взял за основу материалы урока и сделал добавление сообщения при нажатии на кнопку.

Lesson 20 Homework

---

Vyacheslav_Kulik/lesson 20/package-lock.json
Vyacheslav_Kulik/lesson 20/package.json
Vyacheslav_Kulik/lesson 20/src/homework.js
Vyacheslav_Kulik/lesson 20/src/homework2.js
Vyacheslav_Kulik/lesson 20/src/index.html
Vyacheslav_Kulik/lesson 20/src/index.js
Vyacheslav_Kulik/lesson 20/webpack.config.js

Vyacheslav_Kulik/lesson 20/src/homework.js - ДЗ со * с добавлением в массив и выводом в консоль;
Vyacheslav_Kulik/lesson 20/src/homework2.js - ДЗ со * с  добавлением в массив и рендером в браузере.

HomeWork lesson 20. React + webpack + babel. Kulik Vyacheslav

---

Sergey_Nikitin/lesson21/package-lock.json
Sergey_Nikitin/lesson21/package.json
Sergey_Nikitin/lesson21/src/components/App.jsx
Sergey_Nikitin/lesson21/src/components/App2.jsx
Sergey_Nikitin/lesson21/src/components/Counter.jsx
Sergey_Nikitin/lesson21/src/components/Message.jsx
Sergey_Nikitin/lesson21/src/components/MessageForm.jsx
Sergey_Nikitin/lesson21/src/components/MessageList.jsx
Sergey_Nikitin/lesson21/src/components/Messenger.jsx
Sergey_Nikitin/lesson21/src/index.html
Sergey_Nikitin/lesson21/src/index.js
Sergey_Nikitin/lesson21/webpack.config.js

Взяты материалы урока и  реализован автоответ бота с именем последнего автора сообщения

Lesson 21 Homework

---

Sergey_Nikitin/lesson22/package-lock.json
Sergey_Nikitin/lesson22/package.json
Sergey_Nikitin/lesson22/src/components/ChatList/ChatList.css
Sergey_Nikitin/lesson22/src/components/ChatList/ChatList.jsx
Sergey_Nikitin/lesson22/src/components/ChatList/index.js
Sergey_Nikitin/lesson22/src/components/Header/Header.css
Sergey_Nikitin/lesson22/src/components/Header/Header.jsx
Sergey_Nikitin/lesson22/src/components/Header/index.js
Sergey_Nikitin/lesson22/src/components/Layout/Layout.css
Sergey_Nikitin/lesson22/src/components/Layout/Layout.jsx
Sergey_Nikitin/lesson22/src/components/Layout/index.js
Sergey_Nikitin/lesson22/src/components/LayoutGreen/Layout.css
Sergey_Nikitin/lesson22/src/components/LayoutGreen/Layout.jsx
Sergey_Nikitin/lesson22/src/components/LayoutGreen/index.js
Sergey_Nikitin/lesson22/src/components/Message/Message.jsx
Sergey_Nikitin/lesson22/src/components/Message/Message.scss
Sergey_Nikitin/lesson22/src/components/Message/index.js
Sergey_Nikitin/lesson22/src/components/MessageForm/MessageForm.jsx
Sergey_Nikitin/lesson22/src/components/MessageForm/index.js
Sergey_Nikitin/lesson22/src/components/MessageList/MessageList.css
Sergey_Nikitin/lesson22/src/components/MessageList/MessageList.jsx
Sergey_Nikitin/lesson22/src/components/MessageList/index.js
Sergey_Nikitin/lesson22/src/components/Messenger/Messenger.css
Sergey_Nikitin/lesson22/src/components/Messenger/Messenger.jsx
Sergey_Nikitin/lesson22/src/components/Messenger/index.js
Sergey_Nikitin/lesson22/src/index.html
Sergey_Nikitin/lesson22/src/index.js
Sergey_Nikitin/lesson22/webpack.config.js

Использованы материалы урока
Добавлены компоненты Header, ChatList.
реализована отправка по событию Ctrl+Enter
Исправлен бот.

Lesson 22 Homework

---

Sergei_Gerashchenko/React/lesson22/package.json
Sergei_Gerashchenko/React/lesson22/src/components/ChatList/ChatList.css
Sergei_Gerashchenko/React/lesson22/src/components/ChatList/ChatList.jsx
Sergei_Gerashchenko/React/lesson22/src/components/ChatList/index.js
Sergei_Gerashchenko/React/lesson22/src/components/Header/Hader.css
Sergei_Gerashchenko/React/lesson22/src/components/Header/Header.jsx
Sergei_Gerashchenko/React/lesson22/src/components/Header/index.js
Sergei_Gerashchenko/React/lesson22/src/components/Layout/Layout.css
Sergei_Gerashchenko/React/lesson22/src/components/Layout/Layout.jsx
Sergei_Gerashchenko/React/lesson22/src/components/Layout/index.js
Sergei_Gerashchenko/React/lesson22/src/components/Message/Message.jsx
Sergei_Gerashchenko/React/lesson22/src/components/Message/Message.scss
Sergei_Gerashchenko/React/lesson22/src/components/Message/index.js
Sergei_Gerashchenko/React/lesson22/src/components/MessageForm/MessageForm.jsx
Sergei_Gerashchenko/React/lesson22/src/components/MessageForm/index.js
Sergei_Gerashchenko/React/lesson22/src/components/MessageList/MessageList.css
Sergei_Gerashchenko/React/lesson22/src/components/MessageList/MessageList.jsx
Sergei_Gerashchenko/React/lesson22/src/components/MessageList/index.js
Sergei_Gerashchenko/React/lesson22/src/components/Messenger/Messenger.css
Sergei_Gerashchenko/React/lesson22/src/components/Messenger/Messenger.jsx
Sergei_Gerashchenko/React/lesson22/src/components/Messenger/index.js
Sergei_Gerashchenko/React/lesson22/src/index.html
Sergei_Gerashchenko/React/lesson22/src/index.js
Sergei_Gerashchenko/React/lesson22/webpack.config.js

Немного не до разобрался, как в сетке грида сделать второй ряд растянутым по высоте

Homework22

---

Dmitry_Baranov/React/Lesson-3/package.json
Dmitry_Baranov/React/Lesson-3/src/components/ChatList/ChatList.css
Dmitry_Baranov/React/Lesson-3/src/components/ChatList/ChatList.js
Dmitry_Baranov/React/Lesson-3/src/components/ChatList/index.js
Dmitry_Baranov/React/Lesson-3/src/components/Header/Header.css
Dmitry_Baranov/React/Lesson-3/src/components/Header/Header.js
Dmitry_Baranov/React/Lesson-3/src/components/Header/index.js
Dmitry_Baranov/React/Lesson-3/src/components/Layout/Layout.css
Dmitry_Baranov/React/Lesson-3/src/components/Layout/Layout.jsx
Dmitry_Baranov/React/Lesson-3/src/components/Layout/index.js
Dmitry_Baranov/React/Lesson-3/src/components/LayoutGreen/Layout.css
Dmitry_Baranov/React/Lesson-3/src/components/LayoutGreen/Layout.jsx
Dmitry_Baranov/React/Lesson-3/src/components/LayoutGreen/index.js
Dmitry_Baranov/React/Lesson-3/src/components/Message/Message.jsx
Dmitry_Baranov/React/Lesson-3/src/components/Message/Message.scss
Dmitry_Baranov/React/Lesson-3/src/components/Message/index.js
Dmitry_Baranov/React/Lesson-3/src/components/MessageForm/MessageForm.jsx
Dmitry_Baranov/React/Lesson-3/src/components/MessageForm/index.js
Dmitry_Baranov/React/Lesson-3/src/components/MessageList/MessageList.css
Dmitry_Baranov/React/Lesson-3/src/components/MessageList/MessageList.jsx
Dmitry_Baranov/React/Lesson-3/src/components/MessageList/index.js
Dmitry_Baranov/React/Lesson-3/src/components/Messenger/Messenger.css
Dmitry_Baranov/React/Lesson-3/src/components/Messenger/Messenger.jsx
Dmitry_Baranov/React/Lesson-3/src/components/Messenger/index.js
Dmitry_Baranov/React/Lesson-3/src/index.html
Dmitry_Baranov/React/Lesson-3/src/index.js
Dmitry_Baranov/React/Lesson-3/webpack.config.js

Игорь, как при переиспользовании компонента менять ему стили? Сейчас стили для компонента Header написал в самом компоненте, а если надо сменить к примеру цвет или размер шрифта как правильно это реализовать?

React home work 3

---

Aleksandr_Koposov/react2/package-lock.json
Aleksandr_Koposov/react2/package.json
Aleksandr_Koposov/react2/src/components/ChatForm/ChatForm.jsx
Aleksandr_Koposov/react2/src/components/ChatForm/ChatForm.scss
Aleksandr_Koposov/react2/src/components/ChatForm/index.js
Aleksandr_Koposov/react2/src/components/ChatItem/ChatItem.jsx
Aleksandr_Koposov/react2/src/components/ChatItem/ChatItem.scss
Aleksandr_Koposov/react2/src/components/ChatsList/ChatsList.jsx
Aleksandr_Koposov/react2/src/components/Header/Header.jsx
Aleksandr_Koposov/react2/src/components/Header/Header.scss
Aleksandr_Koposov/react2/src/components/Layout/Layout.jsx
Aleksandr_Koposov/react2/src/components/Message/Message.jsx
Aleksandr_Koposov/react2/src/components/MessageForm/MessageForm.jsx
Aleksandr_Koposov/react2/src/components/MessageForm/MessageForm.scss
Aleksandr_Koposov/react2/src/components/MessageList/MessageList.jsx
Aleksandr_Koposov/react2/src/components/MessageList/MessageList.scss
Aleksandr_Koposov/react2/src/components/MessagesBlock/MessagesBlock.jsx
Aleksandr_Koposov/react2/src/components/MessagesBlock/MessagesBlock.scss
Aleksandr_Koposov/react2/src/components/Profile/Profile.jsx
Aleksandr_Koposov/react2/src/components/Profile/Profile.scss
Aleksandr_Koposov/react2/src/components/Profile/index.js
Aleksandr_Koposov/react2/src/index.html
Aleksandr_Koposov/react2/src/index.jsx
Aleksandr_Koposov/react2/webpack.config.js

Очередное обновление react2. Автора убрал из формы сообщения, т.к. пользователь теперь глобальный. Для запуска `npm run dev`

React - ДЗ 4
